name: CI Build, Test, and Push Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests with pytest
        run: PYTHONPATH=. pytest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from Git tag
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ env.IMAGE_TAG }}

      - name: Checkout manifest repository
        uses: actions/checkout@v4
        with:
          repository: raian2209/manifestsCI-PythonAPI
          path: manifestsCI-PythonAPI
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Update Kubernetes manifest
        run: |
          cd manifestsCI-PythonAPI
          sed -i 's|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ env.IMAGE_TAG }}|' deployment.yaml

      - name: Create or Update Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          path: ./manifestsCI-PythonAPI
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Update image to ${{ env.IMAGE_TAG }}"
          branch: "automated-manifest-updates"
          title: "Automated Manifest Update"
          body: |
            Automated image update to version **${{ env.IMAGE_TAG }}**.
            This PR is automatically updated by the CI pipeline.
          delete-branch: true